import type { PackId } from '@/lib/games/relic/scratch';
/** Painted ticket books (generated by scripts/optimize-lucky-art.mjs).
 * `panel` is the empty play panel as x, y, width, height fractions of the
 * trimmed ticket; `aspect` is its width over height. */
export type TicketArt = {
  src: string;
  small: string;
  aspect: number;
  panel: [number, number, number, number];
};
export const TICKET_ART: Record<PackId, TicketArt> = {
  seven: {
    src: '/art/lucky/ticket-seven-v1.webp',
    small: '/art/lucky/ticket-seven-v1-small.webp',
    aspect: 0.6347,
    panel: [0.1272, 0.3988, 0.7457, 0.4227],
  },
  twins: {
    src: '/art/lucky/ticket-twins-v1.webp',
    small: '/art/lucky/ticket-twins-v1-small.webp',
    aspect: 0.6328,
    panel: [0.0942, 0.5163, 0.8116, 0.3137],
  },
  path: {
    src: '/art/lucky/ticket-path-v1.webp',
    small: '/art/lucky/ticket-path-v1-small.webp',
    aspect: 0.6262,
    panel: [0.1713, 0.4797, 0.6553, 0.3611],
  },
  ladder: {
    src: '/art/lucky/ticket-ladder-v1.webp',
    small: '/art/lucky/ticket-ladder-v1-small.webp',
    aspect: 0.4442,
    panel: [0.131, 0.3384, 0.7351, 0.5935],
  },
  mine: {
    src: '/art/lucky/ticket-mine-v1.webp',
    small: '/art/lucky/ticket-mine-v1-small.webp',
    aspect: 0.6645,
    panel: [0.1332, 0.4082, 0.7326, 0.4273],
  },
  sunmoon: {
    src: '/art/lucky/ticket-sunmoon-v1.webp',
    small: '/art/lucky/ticket-sunmoon-v1-small.webp',
    aspect: 1,
    panel: [0.2464, 0.3246, 0.5064, 0.5064],
  },
  chart: {
    src: '/art/lucky/ticket-chart-v1.webp',
    small: '/art/lucky/ticket-chart-v1-small.webp',
    aspect: 1.639,
    panel: [0.4671, 0.1232, 0.4731, 0.7579],
  },
  crown: {
    src: '/art/lucky/ticket-crown-v1.webp',
    small: '/art/lucky/ticket-crown-v1-small.webp',
    aspect: 0.6715,
    panel: [0.1709, 0.3941, 0.6572, 0.4007],
  },
};
export const SYMBOL_SHEET = '/art/lucky/symbols-v1.webp';
