/** Keep Docker's public payload in sync with the assets used by shipped games.
 * --write refreshes the allowlist; --check fails if assets or rules have drifted.
 * Original art and unused candidates remain available in the working repository.
 */
import { readFile, readdir, stat, writeFile } from 'node:fs/promises';
import { dirname } from 'node:path';
import { boxCover } from '../lib/games/box-covers.ts';
import {
  creaturesFor,
  foodsFor,
  tokenImage,
} from '../lib/games/trio/engine.ts';
import { paperWorldFor } from '../lib/games/mora-world.ts';
import { tableWorldFor } from '../lib/games/table-world.ts';
import { ambiences } from '../lib/games/ambience.ts';

const assets = new Set([
  '/favicon.svg',
  '/maps/earth-satellite.jpg',
  '/audio/ambience/CREDITS.md',
]);
const add = (path) => {
  if (path) assets.add(path);
};
const previews = JSON.parse(
  await readFile('lib/artwork-previews.json', 'utf8'),
);
for (const id of [
  'undertow',
  'wildgrove',
  'midnight',
  'orin',
  'miro',
  'relic',
  'folio',
]) {
  const cover = boxCover(id);
  add(cover);
  add(cover.replace('.webp', '-spine.webp'));
  for (const entry of previews[cover].srcSet.split(', '))
    add(entry.split(' ')[0]);
}
for (const set of ['beginner', 'intermediate']) {
  creaturesFor(set).forEach((_, i) => add(tokenImage(i, false, set)));
  foodsFor(set).forEach((_, i) => add(tokenImage(i, true, set)));
}
for (const tall of [false, true]) {
  for (const world of ['observatory', 'floodline']) {
    const art = paperWorldFor(tall, undefined, world);
    for (const key of ['image', 'boardImage', 'overviewImage']) add(art[key]);
  }
  for (const game of ['undertow', 'midnight']) {
    const art = tableWorldFor(game, tall);
    for (const key of ['image', 'overviewImage']) add(art[key]);
  }
}
for (const ambience of ambiences)
  for (const sound of [...ambience.beds, ...ambience.events]) add(sound.src);
const places = JSON.parse(
  await readFile('lib/games/party/geo-places.json', 'utf8'),
);
for (const place of places) add(place.photo);
// Literal URLs in source and CSS complement the dynamic catalogs above.
async function visit(root) {
  for (const entry of await readdir(root, { withFileTypes: true })) {
    if (entry.name === '.DS_Store') continue;
    const path = `${root}/${entry.name}`;
    if (entry.isDirectory()) {
      await visit(path);
      continue;
    }
    if (!/\.(tsx?|css)$/.test(entry.name)) continue;
    const source = await readFile(path, 'utf8');
    for (const match of source.matchAll(
      /['"`](\/(?:art|maps|geography)\/[\w./-]+\.(?:webp|png|jpg|svg|json))['"`]/g,
    ))
      add(match[1]);
  }
}
for (const root of ['app', 'components', 'lib']) await visit(root);
const files = [...assets].sort().map((path) => `public${path}`);
let bytes = 0;
for (const path of files) bytes += (await stat(path)).size;
const dirs = new Set(['public']);
for (const file of files) {
  for (let dir = dirname(file); dir !== '.'; dir = dirname(dir)) dirs.add(dir);
}
if (process.argv.includes('--strict')) {
  async function verifyDirectory(root) {
    for (const entry of await readdir(root, { withFileTypes: true })) {
      const path = `${root}/${entry.name}`;
      if (entry.isDirectory()) await verifyDirectory(path);
      else if (!files.includes(path))
        throw new Error(`Unexpected production asset: ${path}`);
    }
  }
  await verifyDirectory('public');
}
const marker =
  '# Production asset allowlist (generated by scripts/production-assets.mjs).';
const rules = `${marker}\npublic/**\n${[...dirs]
  .sort()
  .map((dir) => `!${dir}/\n${dir}/*`)
  .join('\n')}\n${files.map((file) => `!${file}`).join('\n')}\n`;
const original = await readFile('.dockerignore', 'utf8');
const prefix = original.includes(marker)
  ? original.slice(0, original.indexOf(marker))
  : original.slice(0, original.indexOf('# The production client'));
const updated = `${prefix}${rules}`;
if (process.argv.includes('--write')) await writeFile('.dockerignore', updated);
else if (updated !== original)
  throw new Error(
    'Docker assets changed. Run node scripts/production-assets.mjs --write.',
  );
console.log(
  `${files.length} production assets, ${(bytes / 1024 / 1024).toFixed(2)} MiB; all present and Docker allowlist ${process.argv.includes('--write') ? 'updated' : 'verified'}.`,
);
