/** Original prompts: everyday experiences, nature and imagination; no brands,
 * celebrities, national trivia or purported survey statistics. */
export type Topic = {
  id: number;
  title: string;
  category: string;
  answers: string[];
  /** Retired prompts keep their id so saved games still render them, but are
   * never dealt again. */
  retired?: true;
};
const rows: [string, string, string][] = [
  [
    'Everyday',
    'The best way to spend a free hour',
    'Read a book|Take a walk|Have a nap|Cook something|Call a friend|Draw a picture',
  ],
  [
    'Everyday',
    'Small things that make a morning better',
    'Fresh air|Warm drink|Quiet room|Good music|A long shower|A friendly message',
  ],
  [
    'Everyday',
    'The most annoying little inconvenience',
    'Wet socks|Low battery|A squeaky door|A lost key|A slow queue|A tangled cable',
  ],
  [
    'Everyday',
    'The best sounds to fall asleep to',
    'Rain|Waves|Wind in trees|A fan|A crackling fire|Silence',
  ],
  [
    'Everyday',
    'The nicest surprise to come home to',
    'A clean kitchen|A cooked meal|Fresh flowers|A handwritten note|A happy pet|A parcel',
  ],
  [
    'Everyday',
    'The most satisfying tiny victory',
    'Fixing something|Finding lost money|Catching a train|Finishing a puzzle|Growing a plant|Clearing your inbox',
  ],
  [
    'Everyday',
    'Things worth waking up early for',
    'Sunrise|An empty beach|A trip|Fresh bread|A quiet walk|Time to yourself',
  ],
  [
    'Everyday',
    'The best place to read',
    'In bed|Under a tree|By a window|On a train|In a library|On a balcony',
  ],
  [
    'Everyday',
    'The most useful thing in a pocket',
    'A key|A tissue|A coin|A pen|A small torch|A phone',
  ],
  [
    'Everyday',
    'Chores you mind the least',
    'Washing dishes|Sweeping|Watering plants|Folding clothes|Cooking|Organising shelves',
  ],
  [
    'Everyday',
    'The best rainy-day activity',
    'Bake|Play a game|Watch a film|Make something|Read|Take a nap',
  ],
  [
    'Everyday',
    'The most comforting smell',
    'Fresh bread|Rain on earth|Clean laundry|Citrus peel|Wood smoke|Fresh herbs',
  ],
  [
    'Everyday',
    'The best thing about a day off',
    'No alarm|No schedule|A long breakfast|Seeing friends|Going somewhere new|Doing nothing',
  ],
  [
    'Everyday',
    'The hardest thing to lend someone',
    'A favourite book|Your phone|Your bicycle|A treasured jumper|Your headphones|Your last pen',
  ],
  [
    'Everyday',
    'Little luxuries you would love every day',
    'Fresh sheets|Breakfast in bed|A hot bath|A foot massage|Freshly baked bread|Someone else doing the dishes',
  ],
  [
    'Everyday',
    'The nicest kind of light',
    'Sunrise|Candlelight|Moonlight|A reading lamp|Firelight|Late afternoon sun',
  ],
  [
    'Food',
    'The best fruit to eat fresh',
    'Apple|Banana|Mango|Strawberry|Orange|Watermelon',
  ],
  [
    'Food',
    'The best texture in a snack',
    'Crunchy|Creamy|Chewy|Fluffy|Crispy|Juicy',
  ],
  [
    'Food',
    'The best thing to share at a picnic',
    'Bread|Fruit|Cheese|Nuts|Cake|Salad',
  ],
  [
    'Food',
    'The best flavour in a dessert',
    'Chocolate|Vanilla|Lemon|Caramel|Coconut|Coffee',
  ],
  [
    'Food',
    'The best food on a cold day',
    'Soup|Baked potatoes|Stew|Warm bread|Noodles|Porridge',
  ],
  [
    'Food',
    'The best breakfast ingredient',
    'Eggs|Bread|Yoghurt|Fruit|Oats|Cheese',
  ],
  [
    'Food',
    'The most useful kitchen tool',
    'Knife|Spoon|Pan|Chopping board|Grater|Colander',
  ],
  [
    'Food',
    'The best thing to grow to eat',
    'Tomatoes|Strawberries|Basil|Carrots|Lettuce|Peas',
  ],
  [
    'Food',
    'The best thing to put on bread',
    'Butter|Cheese|Jam|Honey|Hummus|Chocolate spread',
  ],
  [
    'Food',
    'The best refreshing drink',
    'Cold water|Fruit juice|Iced tea|Lemon water|Sparkling water|Smoothie',
  ],
  ['Food', 'The best cooking method', 'Roast|Steam|Grill|Bake|Stir-fry|Simmer'],
  [
    'Food',
    'The best shape for a biscuit',
    'Circle|Star|Heart|Square|Crescent|Animal',
  ],
  [
    'Food',
    'Foods you would take on a walk',
    'Apple|Nuts|Sandwich|Dried fruit|Crackers|Banana',
  ],
  [
    'Food',
    'The best addition to a salad',
    'Cucumber|Tomato|Avocado|Nuts|Cheese|Olives',
  ],
  [
    'Food',
    'The best way to eat a potato',
    'Roasted|Mashed|Baked|Fried|In soup|In salad',
  ],
  [
    'Food',
    'The most inviting food colour',
    'Golden brown|Bright red|Leaf green|Cream white|Deep purple|Sunny yellow',
  ],
  [
    'Nature',
    'The best view from a window',
    'Mountains|Sea|Forest|Garden|River|Open fields',
  ],
  [
    'Nature',
    'Animals you would like to watch',
    'Otters|Penguins|Elephants|Dolphins|Foxes|Owls',
  ],
  [
    'Nature',
    'The best natural place to explore',
    'Forest|Beach|Cave|Mountain|Lake|Desert',
  ],
  [
    'Nature',
    'The most impressive kind of weather',
    'Thunderstorm|Snowfall|Fog|Rainbow|Heavy rain|Strong wind',
  ],
  [
    'Nature',
    'The best thing to find on a walk',
    'A waterfall|A wildflower|An animal track|A great view|An old tree|A hidden path',
  ],
  [
    'Nature',
    'The most calming movement',
    'Waves rolling|Leaves swaying|Clouds drifting|Snow falling|Fish swimming|A stream flowing',
  ],
  [
    'Nature',
    'Animals that would make good guides',
    'Dog|Owl|Dolphin|Elephant|Horse|Fox',
  ],
  [
    'Nature',
    'The most beautiful thing in the night sky',
    'Full moon|Stars|Meteor shower|Aurora|A comet|A crescent moon',
  ],
  [
    'Nature',
    'The best small garden feature',
    'Pond|Flower bed|Herb pots|Fruit tree|Bird bath|Hammock',
  ],
  [
    'Nature',
    'The best thing about a beach',
    'Swimming|Sand|Waves|Shells|Sea air|Sunset',
  ],
  [
    'Nature',
    'The most fascinating tiny creature',
    'Ant|Bee|Butterfly|Spider|Ladybird|Snail',
  ],
  [
    'Nature',
    'The best place to sit outside',
    'Under a tree|On a rock|By water|On grass|On a bench|In a hammock',
  ],
  [
    'Nature',
    'The best thing to collect on a nature walk',
    'Leaves|Stones|Shells|Pine cones|Photographs|Memories',
  ],
  [
    'Nature',
    'The most inviting landscape colour',
    'Ocean blue|Forest green|Sand gold|Snow white|Clay red|Lavender purple',
  ],
  [
    'Nature',
    'The best animal ability to borrow',
    'Flight|Night vision|Breathing underwater|Camouflage|Echolocation|Regrowing a limb',
  ],
  [
    'Nature',
    'The nicest thing after rain',
    'A rainbow|Fresh air|Puddles|Dripping leaves|Soft light|The smell of earth',
  ],
  [
    'Travel',
    'The best part of a journey',
    'Planning|Leaving|The view|Arriving|Meeting people|Coming home',
  ],
  [
    'Travel',
    'The best way to explore a new place',
    'Walk|Cycle|Take a boat|Ride a train|Join a guide|Wander without a map',
  ],
  [
    'Travel',
    'The best place to stay for a night',
    'Treehouse|Tent|Cabin|Boat|Small hotel|Mountain hut',
  ],
  [
    'Travel',
    'The most useful thing to pack',
    'Map|Water bottle|Notebook|Camera|Raincoat|Comfortable shoes',
  ],
  [
    'Travel',
    'The nicest souvenir',
    'Photograph|Recipe|Stone|Postcard|Handmade object|A new friendship',
  ],
  [
    'Travel',
    'The best activity beside a lake',
    'Swim|Read|Paddle|Picnic|Walk|Watch birds',
  ],
  [
    'Travel',
    'The most tempting path',
    'Through trees|Along cliffs|Beside a river|Up a hill|Across a meadow|Into a village',
  ],
  [
    'Travel',
    'The best thing to do with no timetable',
    'Explore|Eat slowly|Sleep|Talk|People-watch|Make a detour',
  ],
  [
    'Travel',
    'The most important thing on a long journey',
    'Comfort|Good company|Scenery|Snacks|Music|Sleep',
  ],
  [
    'Travel',
    'Places you would like to see from above',
    'Coastline|City|Forest|Desert|Mountains|Islands',
  ],
  [
    'Travel',
    'The best slow adventure',
    'A long walk|A cycle trip|A canoe trip|A train journey|A sailing trip|A camping weekend',
  ],
  [
    'Travel',
    'The best place for a secret hideaway',
    'Tree canopy|Cliffside|Lakeshore|Cave|Rooftop|Small island',
  ],
  [
    'Travel',
    'The worst thing to forget on a trip',
    'Shoes|Toothbrush|Charger|Raincoat|Glasses|A book',
  ],
  [
    'Travel',
    'The best time to explore a city',
    'Early morning|Late morning|Midday|Afternoon|Sunset|After dark',
  ],
  [
    'Travel',
    'The most useful skill when travelling',
    'Reading maps|Learning words|Packing lightly|Staying calm|Making friends|Fixing things',
  ],
  [
    'Travel',
    'The best seat on a journey',
    'By the window|Near the door|In the shade|Beside a friend|At the front|With extra legroom',
  ],
  [
    'Imagination',
    'The best superpower for ordinary life',
    'Teleportation|Flying|Talking to animals|Pausing time|Instant tidying|Perfect memory',
  ],
  [
    'Imagination',
    'The best magical door destination',
    'A floating island|An underwater city|A giant library|A moon garden|An enchanted forest|A cloud palace',
  ],
  [
    'Imagination',
    'The best job for a friendly robot',
    'Cook|Gardener|Cleaner|Translator|Pet sitter|Travel guide',
  ],
  [
    'Imagination',
    'The best tiny dragon talent',
    'Lighting candles|Warming tea|Finding keys|Delivering notes|Singing|Growing flowers',
  ],
  [
    'Imagination',
    'The best impossible pet',
    'Pocket elephant|Tiny dragon|Glowing jellyfish|Cloud cat|Talking turtle|Miniature whale',
  ],
  [
    'Imagination',
    'The best room in a magical house',
    'Library|Greenhouse|Observatory|Pool|Workshop|Kitchen',
  ],
  [
    'Imagination',
    'The best thing to make pocket-sized',
    'Bicycle|Bed|Kitchen|Garden|Boat|Library',
  ],
  [
    'Imagination',
    'The best thing to make enormous',
    'A flower|A treehouse|A bubble|A book|A cushion|A strawberry',
  ],
  [
    'Imagination',
    'The best material for a fantasy bridge',
    'Glass|Vines|Clouds|Ice|Giant leaves|Light',
  ],
  [
    'Imagination',
    'The best way to travel through a dream',
    'Fly|Sail|Float in a bubble|Ride a giant bird|Walk through doors|Surf on clouds',
  ],
  [
    'Imagination',
    'The best gift from a wizard',
    'A healing song|A self-filling cup|A flying carpet|A weather charm|A talking book|An endless pocket',
  ],
  [
    'Imagination',
    'The best imaginary sport',
    'Cloud jumping|Dragon racing|Bubble tennis|Moon football|Zero-gravity swimming|Invisible hide-and-seek',
  ],
  [
    'Imagination',
    'The best thing for trees to grow',
    'Books|Lanterns|Biscuits|Musical notes|Blankets|Tiny houses',
  ],
  [
    'Imagination',
    'The best talking object to own',
    'Mirror|Shoes|Kettle|Bicycle|Notebook|Umbrella',
  ],
  [
    'Imagination',
    'The best animal to swap bodies with for a day',
    'Eagle|Dolphin|Cat|Otter|Horse|Butterfly',
  ],
  [
    'Imagination',
    'The best place for a floating home',
    'Above a forest|Above a city|Above the sea|Above mountains|Above a lake|Among clouds',
  ],
  [
    'People',
    'The best quality in a teammate',
    'Patience|Creativity|Honesty|Humour|Courage|Reliability',
  ],
  [
    'People',
    'The best way to help a tired friend',
    'Listen|Make a meal|Give them space|Help with chores|Take them outside|Make them laugh',
  ],
  [
    'People',
    'The best gift that costs nothing',
    'Your time|A kind note|A shared memory|A favour|A song|A good conversation',
  ],
  [
    'People',
    'The best group activity',
    'Cook together|Walk together|Play a game|Make music|Build something|Tell stories',
  ],
  [
    'People',
    'The best compliment to receive',
    'You are kind|You are funny|You are thoughtful|You are creative|You are dependable|You are brave',
  ],
  [
    'People',
    'The best role on an imaginary expedition',
    'Navigator|Cook|Medic|Scout|Inventor|Storyteller',
  ],
  [
    'People',
    'The best way to welcome someone',
    'Offer a drink|Introduce everyone|Show them around|Ask a question|Share food|Give them a comfortable seat',
  ],
  [
    'People',
    'The best thing to teach a friend',
    'A recipe|A language|A craft|A game|A useful repair|A dance',
  ],
  [
    'People',
    'The best reason to celebrate',
    'Finishing a project|Reuniting|Learning something|Helping someone|Trying something scary|An ordinary good day',
  ],
  [
    'People',
    'The best shared challenge',
    'Build a shelter|Solve a puzzle|Cook a feast|Make a short film|Grow a garden|Plan a surprise',
  ],
  [
    'People',
    'The most useful group skill',
    'Listening|Planning|Encouraging|Improvising|Explaining|Noticing details',
  ],
  [
    'People',
    'The best way to keep a memory',
    'Photograph|Diary|Drawing|Voice recording|Keepsake|Story',
  ],
  ['Play', 'The most fun way to move', 'Dance|Swim|Cycle|Climb|Run|Skate'],
  [
    'Play',
    'The best thing to build',
    'Treehouse|Sandcastle|Paper plane|Snow sculpture|Model boat|Blanket fort',
  ],
  [
    'Play',
    'The best puzzle ingredient',
    'Patterns|Words|Numbers|Pictures|Logic|Hidden objects',
  ],
  [
    'Play',
    'The best tool for making art',
    'Pencil|Paintbrush|Clay|Camera|Scissors|Needle and thread',
  ],
  [
    'Play',
    'The best thing to do with an empty box',
    'Make a castle|Make a mask|Store treasures|Make a puppet theatre|Make a robot|Make a maze',
  ],
  [
    'Play',
    'The best toy without batteries',
    'Ball|Kite|Spinning top|Building blocks|Skipping rope|Yo-yo',
  ],
  [
    'Play',
    'The best skill to learn instantly',
    'Play an instrument|Speak a language|Dance|Draw|Juggle|Sing',
  ],
  [
    'Play',
    'The best kind of story',
    'Mystery|Adventure|Comedy|Fantasy|Romance|Science fiction',
  ],
  [
    'Play',
    'The best game-night snack property',
    'Easy to share|Not sticky|Quiet to eat|Crunchy|Sweet|Savoury',
  ],
  [
    'Play',
    'The best harmless competition',
    'Paper-plane flight|Sandcastle building|Puzzle solving|Silly drawing|Stone skipping|Guessing sounds',
  ],
  [
    'Play',
    'The best thing to make from paper',
    'Boat|Flower|Animal|Lantern|Aeroplane|Crown',
  ],
  [
    'Play',
    'The most fun thing to balance',
    'Stones|Books|A spoon|A ball|Blocks|A feather',
  ],
  [
    'Home',
    'The best thing in a cosy room',
    'Soft blanket|Warm lamp|Comfortable chair|Bookshelf|Plants|Thick rug',
  ],
  [
    'Home',
    'The most useful extra room',
    'Workshop|Library|Greenhouse|Music room|Guest room|Exercise room',
  ],
  [
    'Home',
    'The best thing on a balcony',
    'Plants|A chair|A hammock|A little table|Lanterns|A bird feeder',
  ],
  [
    'Home',
    'The best colour for a front door',
    'Red|Blue|Green|Yellow|Purple|Natural wood',
  ],
  [
    'Home',
    'The best place for a nap',
    'Hammock|Sofa|Bed|Shady grass|Window seat|Reclining chair',
  ],
  [
    'Home',
    'The most useful thing to learn to repair',
    'Clothes|Bicycle|Furniture|A leaking tap|A lamp|A bag',
  ],
  [
    'Home',
    'The best shape for a window',
    'Circle|Arch|Square|Tall rectangle|Hexagon|Wide rectangle',
  ],
  [
    'Home',
    'The best thing about a small home',
    'Easy to clean|Everything nearby|Cosy corners|Fewer things|Lower upkeep|Creative storage',
  ],
  [
    'Home',
    'The best thing to hang on a wall',
    'A painting|A map|A mirror|Photographs|A handmade object|A plant',
  ],
  [
    'Home',
    'The best houseplant feature',
    'Big leaves|Flowers|Nice scent|Easy care|Interesting shape|Edible leaves',
  ],
  [
    'Home',
    'The most important feature of a chair',
    'Comfort|Sturdiness|Softness|Light weight|Good looks|Ability to fold',
  ],
  [
    'Home',
    'The best object to inherit',
    'A recipe book|A handmade quilt|A musical instrument|A watch|A photograph album|A tool set',
  ],
  // Conversation starters (23 September 2026): personal, a little revealing,
  // and easy to argue about across the table.
  ['Everyday', 'The worst habit in a housemate', 'Leaving dirty dishes|Being loud late at night|Never buying toilet paper|Borrowing without asking|Endless showers|Leaving every light on'],
  ['Everyday', 'Things you would grab if the house was on fire', 'Photo albums|Your laptop|Your passport|A childhood toy|Jewellery|Your diary'],
  ['Everyday', 'The best part of the weekend', 'Friday night|The Saturday lie-in|Sunday brunch|Seeing friends|An afternoon nap|Having no plans'],
  ['Everyday', 'The most stressful everyday moment', 'Running late|Speaking in a meeting|Forgetting a name|Parallel parking|A call from an unknown number|Splitting the bill'],
  ['Everyday', 'The best guilty pleasure', 'A whole day in bed|Trashy TV|Dessert before dinner|Singing alone in the car|Late-night online shopping|Rewatching the same series'],
  ['Everyday', 'Things worth paying more for', 'A good mattress|Good shoes|Concert tickets|Travel|A good haircut|Good coffee'],
  ['Everyday', 'The worst way to be woken up', 'A loud alarm|A phone call|A pet on your face|Building work outside|Someone opening the curtains|Being freezing cold'],
  ['Everyday', 'The most awkward social moment', 'Forgetting someone’s name|Waving back at someone who wasn’t waving at you|Saying “you too” at the wrong time|A long silence|Being sung happy birthday|Hugging when they went for a handshake'],
  ['Everyday', 'The best excuse to leave a party early', 'An early start tomorrow|Feeling ill|The last train|The pet needs feeding|A headache|Just being honest'],
  ['Everyday', 'The hardest thing to give up for a month', 'Coffee|Your phone|Sugar|Social media|Meat|Music'],
  ['Everyday', 'The most overrated celebration', 'New Year’s Eve|Valentine’s Day|Birthdays|Weddings|Halloween|Gender reveals'],
  ['Everyday', 'The most underrated pleasure', 'A nap|Clean sheets|A good stretch|Cancelled plans|Silence|Sitting in the sun'],
  ['Everyday', 'The worst chore', 'Ironing|Cleaning the bathroom|Doing laundry|Washing dishes|Taking out the bins|Vacuuming'],
  ['Everyday', 'The most satisfying sound', 'Popping bubble wrap|Rain on a window|Opening a can|Crunching leaves|Ice cracking in a drink|A clicky keyboard'],
  ['Everyday', 'What you would do with an extra hour every day', 'Sleep|Exercise|Read|Learn a skill|See friends|Absolutely nothing'],
  ['Everyday', 'The first thing you would do after winning the lottery', 'Buy a house|Travel the world|Quit your job|Share with family|Pay off debts|Throw a huge party'],
  ['Everyday', 'The worst smell', 'Rotten eggs|Wet dog|A forgotten lunchbox|A gym bag|Burnt hair|Smelly feet'],
  ['Everyday', 'The biggest fear', 'Heights|Spiders|Deep water|The dark|Public speaking|Needles'],
  ['Everyday', 'The best way to spend a Sunday', 'A long lie-in|Lunch with family|A walk outdoors|A film marathon|Playing sport|Cleaning the whole house'],
  ['Everyday', 'Things people most often lie about', 'Being on their way|Having read the terms|Liking a gift|Their age|Being fine|Having seen that film'],
  ['Food', 'The best pizza topping', 'Mushrooms|Pineapple|Pepperoni|Olives|Extra cheese|Anchovies'],
  ['Food', 'The best comfort food', 'Pasta|Pizza|Chocolate|Mac and cheese|Soup|Ice cream'],
  ['Food', 'The food you could eat for the rest of your life', 'Pizza|Sushi|Pasta|Burgers|Curry|Tacos'],
  ['Food', 'The most overrated food', 'Avocado toast|Sushi|Truffle|Oysters|Kale|Caviar'],
  ['Food', 'The worst food to eat on a first date', 'Spaghetti|Garlic bread|Ribs|Crab|Corn on the cob|Onion soup'],
  ['Food', 'The best meal of the day', 'Breakfast|Brunch|Lunch|Afternoon snack|Dinner|Midnight snack'],
  ['Food', 'The best thing to eat at 2 a.m.', 'Cold pizza|Cereal|A toastie|Instant noodles|Leftovers|Ice cream from the tub'],
  ['Food', 'The best way to have eggs', 'Scrambled|Fried|Boiled|Poached|Omelette|Not at all'],
  ['Nature', 'The animal you would least like to fight', 'A goose|A chimpanzee|A hippo|A swan|A kangaroo|A honey badger'],
  ['Nature', 'The best pet to have', 'Dog|Cat|Horse|Parrot|Tortoise|Rabbit'],
  ['Nature', 'The best season', 'Spring|Early summer|Late summer|Autumn|Winter|Snowy winter'],
  ['Travel', 'The best kind of holiday', 'Beach|City break|Mountains|Road trip|Cruise|Camping'],
  ['Travel', 'Where you would live for a year', 'A beach hut|A city flat|A mountain cabin|A boat|A castle|A farm'],
  ['Travel', 'The worst travel companion', 'Always late|Complains about everything|Plans every minute|Never plans anything|Snores|Never has cash'],
  ['Travel', 'The best place to live', 'A big city|A small town|The countryside|By the sea|In the mountains|The suburbs'],
  ['Imagination', 'The best time-travel trip', 'See the dinosaurs|Meet your grandparents young|Visit the future|Watch the pyramids being built|Relive your best day|Fix a mistake'],
  ['Imagination', 'The superpower you would secretly regret', 'Reading minds|Invisibility|Super hearing|Seeing the future|Never sleeping|Living forever'],
  ['Imagination', 'Things to bring to a desert island', 'A knife|A best friend|Books|Music|Sun cream|A hammock'],
  ['Imagination', 'The best age to stay forever', 'Seven|Seventeen|Twenty-five|Thirty-five|Fifty|Seventy'],
  ['People', 'The most important thing on a first date', 'Good conversation|Making each other laugh|Good manners|Being on time|Looks|A nice place'],
  ['People', 'The biggest dealbreaker in a partner', 'Rude to waiters|Always on their phone|Always late|Bad hygiene|Hates animals|Chews loudly'],
  ['People', 'The best quality in a best friend', 'Loyalty|Humour|Honesty|Listening|Up for anything|Living nearby'],
  ['People', 'The most attractive quality', 'Humour|Kindness|Confidence|Intelligence|Looks|Ambition'],
  ['People', 'What makes someone instantly likeable', 'A good laugh|Remembering your name|Kindness to strangers|Curiosity|Good stories|Confidence'],
  ['People', 'The most annoying phone habit', 'Loud calls in public|Videos without headphones|Scrolling at dinner|Long voice messages|Leaving you on read|Photographing every meal'],
  ['People', 'The best way to make up after an argument', 'Saying sorry first|A hug|Cooking a meal|Giving space|Talking it through|Laughing about it'],
  ['People', 'The best thing about getting older', 'Knowing yourself|Caring less what people think|Better friends|More money|Grandchildren|Senior discounts'],
  ['People', 'Jobs you could never do', 'Surgeon|Teacher|Stand-up comedian|Night security guard|Call-centre agent|Sewer worker'],
  ['People', 'The dream job for a year', 'Chef|Pilot|Zookeeper|Actor|Park ranger|Baker'],
  ['Play', 'The skill everyone should have', 'Cooking|Swimming|First aid|Budgeting|Changing a tyre|Saying no'],
  ['Play', 'The best thing to do on your birthday', 'A big party|Dinner with close friends|A trip away|Nothing at all|A surprise|A spa day'],
  ['Home', 'The most useful invention in the house', 'Fridge|Washing machine|Dishwasher|Central heating|Wi-Fi|Toilet'],
  ['Home', 'Inventions we could live without', 'Selfie sticks|Autocorrect|Leaf blowers|Push notifications|Hand dryers|Alarm clocks'],
  ['Food', 'The food you would miss most if it disappeared', 'Cheese|Chocolate|Bread|Coffee|Pasta|Crisps'],
  ['Everyday', 'The best way to treat yourself after a hard week', 'A takeaway|A long bath|A bit of shopping|A night out|A lie-in|A film on the sofa'],
  ['People', 'The worst thing a guest can do', 'Arrive early|Stay too late|Bring someone uninvited|Keep their shoes on|Criticise the food|Stay on their phone'],
  ['Travel', 'The worst part of flying', 'Security queues|Tiny seats|Delays|A kicking child behind you|Airport prices|Turbulence'],
  ['Food', 'The most disappointing dessert', 'Fruit salad|Rice pudding|Carrot cake|Jelly|Sorbet|Tiramisu'],
  ['Everyday', 'The most annoying thing on public transport', 'Loud music|Taking two seats|Smelly food|Blocking the doors|Loud phone calls|Pushing on before people get off'],
  ['Everyday', 'The perfect Friday night', 'A night out|Takeaway on the sofa|Dinner with friends|An early night|Gaming|A concert'],
  ['People', 'The best way to spend time with a partner', 'Cooking together|Travelling|Lazy mornings|Long walks|A series together|Trying new restaurants'],
  ['Everyday', 'The hardest thing to say no to', 'Another drink|Dessert|One more episode|A favour|A last-minute plan|A sale'],
  ['Everyday', 'Things you always put off', 'Replying to messages|The dentist|Laundry|Paperwork|Exercise|Going to bed'],
];
/** Flat or odd prompts retired after playtesting (23 September 2026). */
const retired = new Set([
  'The best place to read',
  'The most useful thing in a pocket',
  'The nicest kind of light',
  'The best texture in a snack',
  'The best thing to share at a picnic',
  'The best breakfast ingredient',
  'The most useful kitchen tool',
  'The best thing to grow to eat',
  'The best refreshing drink',
  'The best cooking method',
  'The best shape for a biscuit',
  'Foods you would take on a walk',
  'The best addition to a salad',
  'The most inviting food colour',
  'Animals you would like to watch',
  'The best thing to find on a walk',
  'The most calming movement',
  'Animals that would make good guides',
  'The most beautiful thing in the night sky',
  'The best small garden feature',
  'The most fascinating tiny creature',
  'The best place to sit outside',
  'The best thing to collect on a nature walk',
  'The most inviting landscape colour',
  'The nicest thing after rain',
  'The most useful thing to pack',
  'The best activity beside a lake',
  'The most tempting path',
  'The best thing to do with no timetable',
  'Places you would like to see from above',
  'The best slow adventure',
  'The best place for a secret hideaway',
  'The best time to explore a city',
  'The best magical door destination',
  'The best tiny dragon talent',
  'The best impossible pet',
  'The best room in a magical house',
  'The best thing to make pocket-sized',
  'The best thing to make enormous',
  'The best material for a fantasy bridge',
  'The best way to travel through a dream',
  'The best imaginary sport',
  'The best thing for trees to grow',
  'The best talking object to own',
  'The best place for a floating home',
  'The best way to welcome someone',
  'The best thing to teach a friend',
  'The best shared challenge',
  'The most useful group skill',
  'The best thing to build',
  'The best puzzle ingredient',
  'The best tool for making art',
  'The best thing to do with an empty box',
  'The best toy without batteries',
  'The best game-night snack property',
  'The best harmless competition',
  'The best thing to make from paper',
  'The most fun thing to balance',
  'The best thing on a balcony',
  'The best colour for a front door',
  'The most useful thing to learn to repair',
  'The best shape for a window',
  'The best thing about a small home',
  'The best thing to hang on a wall',
  'The best houseplant feature',
  'The most important feature of a chair',
  // Retired because reason rather than taste settles them.
  'The best food on a cold day',
  'The most important thing on a long journey',
  'The worst thing to forget on a trip',
  'The most useful skill when travelling',
  'The best job for a friendly robot',
  'The best gift from a wizard',
  'The best quality in a teammate',
  'The best role on an imaginary expedition',
  'The most useful extra room',
  'Things people most often lie about',
  'The most overrated food',
  'The worst food to eat on a first date',
  'The animal you would least like to fight',
  'Things to bring to a desert island',
  'The skill everyone should have',
  'The most useful invention in the house',
  'Inventions we could live without',
]);
export const topics: Topic[] = rows.map(([category, title, answers], id) => ({
  id,
  category,
  title,
  answers: answers.split('|'),
  ...(retired.has(title) ? { retired: true as const } : {}),
}));
/** Topic ids that may still be dealt. */
export const liveTopicIds = topics.flatMap((t) => (t.retired ? [] : [t.id]));
