/** Sizes' silhouettes: animals, objects and landmarks, each measured along
 * one dimension of its silhouette. `axis` says which side of the silhouette's
 * bounding box that dimension spans (`h` height, `w` width), so a silhouette
 * scaled to `real` metres along that side is at true scale. Figures are
 * typical adult or standard sizes, rounded the way a reference book would;
 * the reveal prints them. `sheet` and `cell` place the silhouette in
 * `public/art/optimized/sizes-sil-{sheet}-v1.webp`, a 4×4 grid read left to
 * right, top to bottom; `size-silhouettes.json` holds each cell's box. */
export type SizeSheet = 'animals' | 'objects' | 'landmarks';
export type SizeDimension = 'height' | 'length' | 'wingspan';
export type SizeThing = {
  id: string;
  name: string;
  /** A short qualifier shown after the name: "(adult)", "(Paris)". */
  sub?: string;
  sheet: SizeSheet;
  cell: number;
  axis: 'h' | 'w';
  dimension: SizeDimension;
  /** Metres along `axis`. */
  real: number;
  /** Shown with the answer. */
  fact: string;
};
const t = (
  id: string,
  name: string,
  sub: string | undefined,
  sheet: SizeSheet,
  cell: number,
  axis: 'h' | 'w',
  dimension: SizeDimension,
  real: number,
  fact: string,
): SizeThing => ({
  id,
  name,
  ...(sub ? { sub } : {}),
  sheet,
  cell,
  axis,
  dimension,
  real,
  fact,
});
export const things: SizeThing[] = [
  t(
    'cat',
    'House cat',
    undefined,
    'animals',
    0,
    'w',
    'length',
    0.75,
    'Nose to tail tip, a house cat measures about 75 cm; the tail is roughly 30 cm of it.',
  ),
  t(
    'penguin',
    'Emperor penguin',
    undefined,
    'animals',
    1,
    'h',
    'height',
    1.15,
    'The emperor is the tallest penguin alive, standing about 1.15 m.',
  ),
  t(
    'eagle',
    'Bald eagle',
    undefined,
    'animals',
    2,
    'w',
    'wingspan',
    2,
    'A bald eagle’s wings span about 2 m, wider than most people are tall.',
  ),
  t(
    'person',
    'Person',
    '(adult)',
    'animals',
    3,
    'h',
    'height',
    1.75,
    'An adult man stands about 1.75 m tall on average in much of the world.',
  ),
  t(
    'ostrich',
    'Ostrich',
    undefined,
    'animals',
    4,
    'h',
    'height',
    2.5,
    'The ostrich is the tallest bird alive, at about 2.5 m.',
  ),
  t(
    'horse',
    'Horse',
    undefined,
    'animals',
    5,
    'w',
    'length',
    2.5,
    'A riding horse measures about 2.5 m from nose to tail.',
  ),
  t(
    'shark',
    'Great white shark',
    undefined,
    'animals',
    6,
    'w',
    'length',
    4.5,
    'Adult great white sharks are typically about 4.5 m long; females grow larger than males.',
  ),
  t(
    'crocodile',
    'Saltwater crocodile',
    '(adult male)',
    'animals',
    7,
    'w',
    'length',
    5,
    'Male saltwater crocodiles commonly reach 5 m, making them the largest living reptiles.',
  ),
  t(
    'hippo',
    'Hippopotamus',
    undefined,
    'animals',
    8,
    'w',
    'length',
    4,
    'An adult hippo is about 4 m long and can weigh as much as a small truck.',
  ),
  t(
    'polar-bear',
    'Polar bear',
    '(adult male)',
    'animals',
    9,
    'w',
    'length',
    2.5,
    'A male polar bear measures about 2.5 m from nose to tail.',
  ),
  t(
    'elephant',
    'African elephant',
    '(adult male)',
    'animals',
    10,
    'h',
    'height',
    3.2,
    'A bull African elephant stands about 3.2 m at the shoulder, the tallest of any elephant.',
  ),
  t(
    'giraffe',
    'Giraffe',
    '(adult male)',
    'animals',
    11,
    'h',
    'height',
    5.5,
    'A bull giraffe can stand 5.5 m tall, the tallest land animal alive.',
  ),
  t(
    't-rex',
    'Tyrannosaurus rex',
    undefined,
    'animals',
    12,
    'w',
    'length',
    12.3,
    '“Sue”, the most complete T. rex skeleton found, is about 12.3 m long.',
  ),
  t(
    'diplodocus',
    'Diplodocus',
    undefined,
    'animals',
    13,
    'w',
    'length',
    26,
    'Diplodocus reached about 26 m, much of it neck and a whip-like tail.',
  ),
  t(
    'blue-whale',
    'Blue whale',
    undefined,
    'animals',
    14,
    'w',
    'length',
    25,
    'Blue whales are commonly about 25 m long and the heaviest animals ever known.',
  ),
  t(
    'kangaroo',
    'Red kangaroo',
    '(adult male)',
    'animals',
    15,
    'h',
    'height',
    1.8,
    'A male red kangaroo standing upright can reach about 1.8 m.',
  ),

  t(
    'banana',
    'Banana',
    undefined,
    'objects',
    0,
    'w',
    'length',
    0.2,
    'A typical supermarket banana is about 20 cm long.',
  ),
  t(
    'phone',
    'Smartphone',
    undefined,
    'objects',
    1,
    'h',
    'height',
    0.15,
    'Most smartphones today are about 15 cm tall.',
  ),
  t(
    'can',
    'Soda can',
    '(330 ml)',
    'objects',
    2,
    'h',
    'height',
    0.12,
    'A standard 330 ml can stands about 12 cm tall.',
  ),
  t(
    'guitar',
    'Acoustic guitar',
    undefined,
    'objects',
    3,
    'h',
    'height',
    1,
    'A full-size acoustic guitar is about 1 m from the base to the headstock.',
  ),
  t(
    'bicycle',
    'Bicycle',
    undefined,
    'objects',
    4,
    'w',
    'length',
    1.75,
    'An adult bicycle measures about 1.75 m from wheel to wheel.',
  ),
  t(
    'piano',
    'Grand piano',
    '(concert grand)',
    'objects',
    5,
    'w',
    'length',
    2.74,
    'A concert grand piano is about 2.74 m long.',
  ),
  t(
    'car',
    'Family car',
    '(hatchback)',
    'objects',
    6,
    'w',
    'length',
    4.2,
    'A family hatchback is about 4.2 m long.',
  ),
  t(
    'bus',
    'Double-decker bus',
    '(London)',
    'objects',
    7,
    'w',
    'length',
    11.2,
    'London’s newest double-deckers are 11.2 m long and 4.4 m tall.',
  ),
  t(
    'truck',
    'Semi-trailer truck',
    '(Europe)',
    'objects',
    8,
    'w',
    'length',
    16.5,
    'European rules cap a tractor and semi-trailer at 16.5 m long.',
  ),
  t(
    'balloon',
    'Hot-air balloon',
    undefined,
    'objects',
    9,
    'h',
    'height',
    20,
    'A typical passenger hot-air balloon is about 20 m tall from basket to crown.',
  ),
  t(
    'jumbo',
    'Boeing 747',
    '(747-400)',
    'objects',
    10,
    'w',
    'length',
    70.7,
    'The 747-400 is 70.7 m long, a little more than its 64.4 m wingspan.',
  ),
  t(
    'saturn',
    'Saturn V rocket',
    undefined,
    'objects',
    11,
    'h',
    'height',
    110.6,
    'The Saturn V that flew astronauts to the Moon stood 110.6 m tall.',
  ),
  t(
    'zeppelin',
    'Hindenburg airship',
    undefined,
    'objects',
    12,
    'w',
    'length',
    245,
    'The Hindenburg was 245 m long, the largest aircraft ever flown.',
  ),
  t(
    'titanic',
    'Titanic',
    undefined,
    'objects',
    13,
    'w',
    'length',
    269,
    'The Titanic was 269 m long, the largest ship afloat when it sailed in 1912.',
  ),
  t(
    'carrier',
    'Aircraft carrier',
    '(Nimitz class)',
    'objects',
    14,
    'w',
    'length',
    333,
    'A Nimitz-class aircraft carrier is 333 m long.',
  ),
  t(
    'racket',
    'Tennis racket',
    undefined,
    'objects',
    15,
    'h',
    'height',
    0.69,
    'A standard adult tennis racket is about 69 cm long.',
  ),

  t(
    'moai',
    'Moai',
    '(Easter Island)',
    'landmarks',
    0,
    'h',
    'height',
    4,
    'Easter Island’s moai average about 4 m tall; the largest ever raised is nearly 10 m.',
  ),
  t(
    'stonehenge',
    'Stonehenge trilithon',
    undefined,
    'landmarks',
    1,
    'h',
    'height',
    7.3,
    'Stonehenge’s Great Trilithon rises about 7.3 m above the ground.',
  ),
  t(
    'redeemer',
    'Christ the Redeemer',
    '(Rio de Janeiro)',
    'landmarks',
    2,
    'h',
    'height',
    38,
    'Christ the Redeemer is 30 m tall on an 8 m pedestal.',
  ),
  t(
    'colosseum',
    'Colosseum',
    '(Rome)',
    'landmarks',
    3,
    'h',
    'height',
    48,
    'The Colosseum’s outer wall stands about 48 m high.',
  ),
  t(
    'arc',
    'Arc de Triomphe',
    '(Paris)',
    'landmarks',
    4,
    'h',
    'height',
    50,
    'The Arc de Triomphe is 50 m tall.',
  ),
  t(
    'pisa',
    'Leaning Tower of Pisa',
    undefined,
    'landmarks',
    5,
    'h',
    'height',
    56,
    'The Leaning Tower of Pisa is about 56 m tall, a little less on its low side.',
  ),
  t(
    'taj',
    'Taj Mahal',
    '(Agra)',
    'landmarks',
    6,
    'h',
    'height',
    73,
    'The Taj Mahal rises 73 m from its platform to the tip of its finial.',
  ),
  t(
    'liberty',
    'Statue of Liberty',
    '(New York)',
    'landmarks',
    7,
    'h',
    'height',
    93,
    'From the ground to the torch, the Statue of Liberty is 93 m tall.',
  ),
  t(
    'big-ben',
    'Elizabeth Tower',
    '(Big Ben, London)',
    'landmarks',
    8,
    'h',
    'height',
    96,
    'The Elizabeth Tower, home of Big Ben, is 96 m tall.',
  ),
  t(
    'pyramid',
    'Great Pyramid of Giza',
    undefined,
    'landmarks',
    9,
    'h',
    'height',
    139,
    'The Great Pyramid stands about 139 m today; it was nearly 147 m when built.',
  ),
  t(
    'needle',
    'Space Needle',
    '(Seattle)',
    'landmarks',
    10,
    'h',
    'height',
    184,
    'Seattle’s Space Needle is 184 m tall.',
  ),
  t(
    'eiffel',
    'Eiffel Tower',
    '(Paris)',
    'landmarks',
    11,
    'h',
    'height',
    330,
    'The Eiffel Tower is 330 m tall with its antennas, and grows in summer heat.',
  ),
  t(
    'empire',
    'Empire State Building',
    '(New York)',
    'landmarks',
    12,
    'h',
    'height',
    443,
    'The Empire State Building reaches 443 m to the tip of its spire.',
  ),
  t(
    'skytree',
    'Tokyo Skytree',
    undefined,
    'landmarks',
    13,
    'h',
    'height',
    634,
    'Tokyo Skytree is 634 m tall, the tallest tower in the world.',
  ),
  t(
    'burj',
    'Burj Khalifa',
    '(Dubai)',
    'landmarks',
    14,
    'h',
    'height',
    828,
    'The Burj Khalifa is 828 m tall, the tallest building in the world.',
  ),
  t(
    'fuji',
    'Mount Fuji',
    undefined,
    'landmarks',
    15,
    'h',
    'height',
    3776,
    'Mount Fuji rises to 3,776 m, the highest peak in Japan.',
  ),
];
