/** Dial spectrums: two opposite ends of a scale. The clue-giver names something
 * that sits at the hidden point between them. Original pairs; no brands.
 * Ids are row positions, so rows are only ever appended or retired. */
export type Spectrum = { id: number; left: string; right: string; retired?: true };
const rows: [string, string][] = [
  ['Cold', 'Hot'],
  ['Underrated', 'Overrated'],
  ['Useless', 'Useful'],
  ['Boring', 'Exciting'],
  ['Cheap', 'Expensive'],
  ['Relaxing', 'Stressful'],
  ['Healthy', 'Unhealthy'],
  ['Normal', 'Weird'],
  ['Bad habit', 'Good habit'],
  ['Easy to learn', 'Hard to learn'],
  ['Forgettable', 'Unforgettable'],
  ['Guilty pleasure', 'Proud pleasure'],
  ['Childish', 'Grown-up'],
  ['Quiet', 'Loud'],
  ['Tastes bad', 'Tastes good'],
  ['Safe', 'Dangerous'],
  ['Rough', 'Smooth'],
  ['Old-fashioned', 'Modern'],
  ['Sad song', 'Happy song'],
  ['Morning person thing', 'Night owl thing'],
  ['Introvert activity', 'Extrovert activity'],
  ['Villain', 'Hero'],
  ['Worst date idea', 'Best date idea'],
  ['Easy job', 'Hard job'],
  ['Needs no skill', 'Needs lots of skill'],
  ['Tiny', 'Huge'],
  ['Scary', 'Cute'],
  ['Unpopular opinion', 'Popular opinion'],
  ['Worth waiting for', 'Not worth waiting for'],
  ['Summer', 'Winter'],
  ['City', 'Countryside'],
  ['Messy', 'Tidy'],
  ['Romantic', 'Unromantic'],
  ['Mild', 'Spicy'],
  ['Overpriced', 'Bargain'],
  ['Short-lived', 'Lasts forever'],
  ['Talent', 'Luck'],
  ['Nobody needs it', 'Everybody needs it'],
  ['Embarrassing', 'Impressive'],
  ['Comfortable', 'Uncomfortable'],
  ['Lazy', 'Hard-working'],
  ['Ugly', 'Beautiful'],
  ['Simple', 'Complicated'],
  ['Rude', 'Polite'],
  ['Common', 'Rare'],
  ['Soft', 'Hard'],
  ['Fragile', 'Indestructible'],
  ['Slow', 'Fast'],
  ['Calm animal', 'Wild animal'],
  ['Breakfast food', 'Dinner food'],
  ['Hobby', 'Job'],
  ['Fantasy', 'Reality'],
  ['Wet', 'Dry'],
  ['Dirty', 'Clean'],
  ['Mean', 'Kind'],
  ['Dull gift', 'Amazing gift'],
  ['Better alone', 'Better with friends'],
  ['Smells bad', 'Smells good'],
  ['Sweet', 'Savoury'],
  ['Weak superpower', 'Strong superpower'],
  ['For kids', 'For adults'],
  ['Clichéd', 'Original'],
  ['Serious', 'Silly'],
  ['Bad film', 'Great film'],
  ['Rarely used', 'Used every day'],
  ['Hard to spell', 'Easy to spell'],
  ['Mainstream', 'Niche'],
  ['Traditional', 'Trendy'],
  ['Harmless', 'Harmful'],
  ['Relaxing holiday', 'Adventure holiday'],
  ['Worst smell', 'Best smell'],
  ['Unfashionable', 'Fashionable'],
  ['Dog person', 'Cat person'],
  ['Low-maintenance', 'High-maintenance'],
  ['Easy to draw', 'Hard to draw'],
  ['Sounds fake', 'Sounds real'],
  ['Good first job', 'Bad first job'],
  ['Friend', 'Enemy'],
  ['Past', 'Future'],
  ['Nature', 'Technology'],
  ['Chore', 'Treat'],
  ['Waste of money', 'Worth every penny'],
  ['Better cold', 'Better hot'],
  ['Dumb idea', 'Genius idea'],
  ['Totally normal', 'Red flag'],
  ['Easy to forgive', 'Hard to forgive'],
  ['Would never try', 'Would try tomorrow'],
  ['Bad advice', 'Good advice'],
];
/** Retired after playtesting (23 September 2026): open-ended magnitudes with no
 * shared frame ("fast compared to what?"), where a snail and a rocket both fit,
 * plus near-duplicates of other rows. A spectrum belongs only if the table
 * agrees on what its two ends mean. */
const retired = new Set([
  'Slow',
  'Tiny',
  'Cheap',
  'Quiet',
  'Rough',
  'Soft',
  'Wet',
  'Fragile',
  'Short-lived',
  'Common',
  'Past',
  'Harmless',
  'Worst smell',
]);
export const spectrums: Spectrum[] = rows.map(([left, right], id) => ({
  id,
  left,
  right,
  ...(retired.has(left) ? { retired: true as const } : {}),
}));
export const liveSpectrumIds = spectrums.flatMap((s) =>
  s.retired ? [] : [s.id],
);
